# Generated by Django 3.1.3 on 2020-11-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instausers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instausers.profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
